import CategoryGrid from "components/CategoryGrid";
import Header from "components/Header";
import TwoSideBarsLayout from "features/layouts/TwoSideBarsLayout";
import ItemCard from "features/shoppingList/ItemCard";
import ShoppingList from "features/shoppingList/ShoppingList";
import Head from "next/head";
import IProduct from "types/Product";
import { useEffect, useState } from "react";
import useProductsToCategories from "hooks/useProductsToCategories";
import { IShoppingListItem } from "types/ShoppingList";

export default function Home() {
  const [products, setProducts] = useState<IShoppingListItem[]>([]);
  const categories = useProductsToCategories(products);

  useEffect(() => {
    setProducts([
      {
        name: "Avocado",
        quantity: 1,
        completed: false,
        category: { name: "Fruits and vegetables" },
      },
      {
        name: "Avocado2",
        quantity: 1,
        completed: false,
        category: { name: "Fruits and vegetables" },
      },
      {
        name: "Avocado5",
        quantity: 1,
        completed: false,
        category: { name: "Fruits and vegetables" },
      },
      {
        name: "Avocado3",
        quantity: 1,
        completed: false,
        category: { name: "Fruits and vegetables" },
      },
    ]);
    return () => {};
  }, []);
  return (
    <div className="">
      <Head>
        <title>Shoppingify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={"/img/favicon.ico"} />
      </Head>

      <TwoSideBarsLayout sideDrawer={<ShoppingList />}>
        <div className="min-h-screen p-2 sm:p-4 md:p-6">
          <Header />
          <div className="mt-4 sm:mt-6 md:mt-8">
            {categories.map((category) => (
              <CategoryGrid key={category._id} name={category.name}>
                {category.items.map((item) => (
                  <ItemCard key={item._id} item={item} />
                ))}
              </CategoryGrid>
            ))}
          </div>
        </div>
      </TwoSideBarsLayout>
    </div>
  );
}
