import CategoryGrid from "components/CategoryGrid";
import Header from "components/Header";
import TwoSideBarsLayout from "components/layouts/TwoSideBarsLayout";
import ItemCard from "features/shoppingList/ItemCard";
import ShoppingList from "features/shoppingList/ShoppingList";
import Head from "next/head";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Shoppingify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={"/img/favicon.ico"} />
      </Head>

      <TwoSideBarsLayout sideDrawer={<ShoppingList />}>
        <div className="min-h-screen p-2 sm:p-4 md:p-6">
          <Header />
          <div className="mt-4 sm:mt-6 md:mt-8">
            <CategoryGrid name="Fruits and vegetables">
              {[
                "Avocado",
                "Banana",
                "Carrots",
                "Chicken",
                "Watermelon",
                "Meat",
              ].map((item) => (
                <ItemCard
                  key={item}
                  text={item}
                  onAddBtnClick={() => {
                    alert("todo");
                  }}
                  onItemBtnClick={() => {
                    alert("todo");
                  }}
                />
              ))}
            </CategoryGrid>
          </div>
        </div>
      </TwoSideBarsLayout>
    </div>
  );
}
