import Layout from "components/layouts/Layout";
import Head from "next/head";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={"/favicon.ico"} />
      </Head>

      TODO
      {/* <Layout>
        <div className="w-full h-screen bg-blue-300">
          ff
        </div>
      </Layout> */}
    </div>
  );
}
